# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DB_NAME: jpaLibraryManager

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      mssql:
        # Docker Hub image
        image: mcr.microsoft.com/mssql/server
        # Provide the password for postgres
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.CI_MSSQL_SA_PASSWORD }}
        ports:
          - 14330:1433
          
    steps:
      - uses: actions/checkout@v2

      - name: Create needed database on mssql container
        run: docker exec -d mssql "create database ${{ env.DB_NAME }}"

      - name: Clean compile and run tests
        run: sudo mvn clean package
